# === General Settings ===
vsync = true;
backend = "glx";
fading = false;
use-damage = true;
glx-no-stencil = true;
glx-no-rebind-pixmap = true;
xrender-sync-fence = true;
experimental-backends = true;

# === Shadow Settings ===
shadow = true;
shadow-red = 0.0;
shadow-green = 0.0;
shadow-blue = 0.0;
shadow-radius = 7;
shadow-offset-x = -6;
shadow-offset-y = -6;
shadow-opacity = 0.65;
crop-shadow-to-monitor = true;
shadow-exclude = [
    "class_g = 'Polybar'"
];

# === Opacity Settings ===
active-opacity = 0.95;
inactive-opacity = 0.95;
opacity-rule = [
  "100:class_g = 'Google-chrome'",
  "100:class_g = 'Brave-browser'",
  "100:class_g = 'VSCodium'",
  "100:class_g = 'vlc'",
  "85:class_g = 'Polybar'"
]

# === Blur Settings ===
blur-method = "dual_kawase";
blur-strength = 4.5;
blur-background = true;
blur-background-exclude = [
  "class_g = 'Google-chrome'",
  "class_g = 'Brave-browser'",
  "class_g = 'VSCodium'",
  "class_g = 'vlc'"
];

# === Window Appearance ===
corner-radius = 4.5;
rounded-corners = true;

# === Other Settings ===
wintypes:
{
  tooltip = { rounded-corners = false };
  menu = { shadow = false; blur-background = false;};
  dnd = { shadow = false; };
};


